CREATE TABLE daily_log (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    log_date DATE NOT NULL,
    raw_text TEXT NULL,
    study_hours DECIMAL(5, 2) NOT NULL DEFAULT 0,
    work_hours DECIMAL(5, 2) NOT NULL DEFAULT 0,
    sleep_hours DECIMAL(5, 2) NOT NULL DEFAULT 0,
    exercise_minutes INT NOT NULL DEFAULT 0,
    entertainment_minutes INT NOT NULL DEFAULT 0,
    mood_tag VARCHAR(64) NULL,
    task_completion_rate INT NULL,
    completed_content TEXT NULL,
    problem_text TEXT NULL,
    reflection_text TEXT NULL,
    parsed_json JSON NULL,
    source_type VARCHAR(32) NOT NULL DEFAULT 'FORM',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_daily_log_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE,
    CONSTRAINT uk_daily_log_user_date UNIQUE (user_id, log_date),
    CONSTRAINT chk_daily_log_study_hours CHECK (study_hours >= 0),
    CONSTRAINT chk_daily_log_work_hours CHECK (work_hours >= 0),
    CONSTRAINT chk_daily_log_sleep_hours CHECK (sleep_hours >= 0),
    CONSTRAINT chk_daily_log_exercise_minutes CHECK (exercise_minutes >= 0),
    CONSTRAINT chk_daily_log_entertainment_minutes CHECK (entertainment_minutes >= 0),
    CONSTRAINT chk_daily_log_task_completion_rate CHECK (
        task_completion_rate IS NULL OR (task_completion_rate >= 0 AND task_completion_rate <= 100)
    ),
    CONSTRAINT chk_daily_log_source_type CHECK (source_type IN ('FORM', 'NATURAL_LANGUAGE', 'MIXED')),
    INDEX idx_daily_log_user_id (user_id),
    INDEX idx_daily_log_log_date (log_date)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE daily_score (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    daily_log_id BIGINT NOT NULL,
    log_date DATE NOT NULL,
    daily_score DECIMAL(5, 2) NOT NULL,
    growth_score DECIMAL(5, 2) NOT NULL,
    execution_score DECIMAL(5, 2) NOT NULL,
    energy_score DECIMAL(5, 2) NOT NULL,
    mood_score DECIMAL(5, 2) NOT NULL,
    distraction_score DECIMAL(5, 2) NOT NULL,
    reflection_score DECIMAL(5, 2) NOT NULL,
    rating VARCHAR(8) NOT NULL,
    reason_json JSON NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_daily_score_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE,
    CONSTRAINT fk_daily_score_daily_log FOREIGN KEY (daily_log_id) REFERENCES daily_log (id) ON DELETE CASCADE,
    CONSTRAINT uk_daily_score_user_date UNIQUE (user_id, log_date),
    CONSTRAINT chk_daily_score_daily_score CHECK (daily_score >= 0 AND daily_score <= 100),
    CONSTRAINT chk_daily_score_growth_score CHECK (growth_score >= 0 AND growth_score <= 100),
    CONSTRAINT chk_daily_score_execution_score CHECK (execution_score >= 0 AND execution_score <= 100),
    CONSTRAINT chk_daily_score_energy_score CHECK (energy_score >= 0 AND energy_score <= 100),
    CONSTRAINT chk_daily_score_mood_score CHECK (mood_score >= 0 AND mood_score <= 100),
    CONSTRAINT chk_daily_score_distraction_score CHECK (distraction_score >= 0 AND distraction_score <= 100),
    CONSTRAINT chk_daily_score_reflection_score CHECK (reflection_score >= 0 AND reflection_score <= 100),
    CONSTRAINT chk_daily_score_rating CHECK (rating IN ('S', 'A', 'B', 'C', 'D', 'E')),
    INDEX idx_daily_score_user_id (user_id),
    INDEX idx_daily_score_daily_log_id (daily_log_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
