CREATE TABLE llm_feedback (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    daily_log_id BIGINT NULL,
    log_date DATE NULL,
    feedback_type VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    prompt TEXT NULL,
    response TEXT NULL,
    fallback_response TEXT NULL,
    model_name VARCHAR(128) NULL,
    error_message VARCHAR(1024) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_llm_feedback_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE,
    CONSTRAINT fk_llm_feedback_daily_log FOREIGN KEY (daily_log_id) REFERENCES daily_log (id) ON DELETE CASCADE,
    CONSTRAINT chk_llm_feedback_type CHECK (feedback_type IN (
        'PARSE_LOG',
        'DAILY_FEEDBACK',
        'TOMORROW_TASKS',
        'WEEKLY_REPORT',
        'STORY'
    )),
    CONSTRAINT chk_llm_feedback_status CHECK (status IN ('PENDING', 'SUCCESS', 'FAILED', 'FALLBACK')),
    INDEX idx_llm_feedback_user_date (user_id, log_date),
    INDEX idx_llm_feedback_daily_log_id (daily_log_id),
    INDEX idx_llm_feedback_type_status (feedback_type, status)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE tomorrow_task (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    source_daily_log_id BIGINT NULL,
    task_date DATE NOT NULL,
    task_type VARCHAR(64) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(1024) NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'TODO',
    generated_by VARCHAR(32) NOT NULL DEFAULT 'RULE',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_tomorrow_task_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE,
    CONSTRAINT fk_tomorrow_task_source_log FOREIGN KEY (source_daily_log_id) REFERENCES daily_log (id) ON DELETE SET NULL,
    CONSTRAINT chk_tomorrow_task_type CHECK (task_type IN ('MAIN', 'SIDE', 'DEFENSE')),
    CONSTRAINT chk_tomorrow_task_status CHECK (status IN ('TODO', 'DONE', 'SKIPPED')),
    CONSTRAINT chk_tomorrow_task_generated_by CHECK (generated_by IN ('LLM', 'RULE')),
    INDEX idx_tomorrow_task_user_date (user_id, task_date),
    INDEX idx_tomorrow_task_source_log (source_daily_log_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;

CREATE TABLE weekly_report (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    week_start_date DATE NOT NULL,
    week_end_date DATE NOT NULL,
    highest_score DECIMAL(5, 2) NULL,
    lowest_score DECIMAL(5, 2) NULL,
    average_score DECIMAL(5, 2) NULL,
    main_enemy VARCHAR(128) NULL,
    growth_summary TEXT NULL,
    suggestion_text TEXT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'GENERATED',
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_weekly_report_user FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE,
    CONSTRAINT uk_weekly_report_user_week UNIQUE (user_id, week_start_date, week_end_date),
    CONSTRAINT chk_weekly_report_date_range CHECK (week_start_date <= week_end_date),
    CONSTRAINT chk_weekly_report_highest_score CHECK (highest_score IS NULL OR (highest_score >= 0 AND highest_score <= 100)),
    CONSTRAINT chk_weekly_report_lowest_score CHECK (lowest_score IS NULL OR (lowest_score >= 0 AND lowest_score <= 100)),
    CONSTRAINT chk_weekly_report_average_score CHECK (average_score IS NULL OR (average_score >= 0 AND average_score <= 100)),
    CONSTRAINT chk_weekly_report_status CHECK (status IN ('GENERATING', 'GENERATED', 'FALLBACK', 'FAILED')),
    INDEX idx_weekly_report_user_id (user_id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
